### ISSUE TITLE
CORS settings on the webapp are blocking signup

### ISSUE THREAD

**Issue by timstokman** [LibreLingo/LibreLingo#3289] opened 2024-02-12 09:20 UTC
I'm unable to signup on https://librelingo.app/sign-up/ with firefox (and also on chrome), the CORS settings are blocking the signup. Just FYI.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://auth.librelingo.app/register. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 530.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://auth.librelingo.app/register. (Reason: CORS request did not succeed). Status code: (null).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://auth.librelingo.app/register. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 530.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://auth.librelingo.app/register. (Reason: CORS request did not succeed). Status code: (null).

![image](https://github.com/LibreLingo/LibreLingo/assets/41363/4ba3d908-742b-4dcd-a984-3c0add2ccb95)

**Comment by Gison43** [comment] 2024-03-03 20:42
I'm in the same boat...trying to signup with Opera browser but it just idles.

**Comment by kantord** [comment] 2024-04-28 20:38
duplicate of https://github.com/LibreLingo/LibreLingo/issues/3092

**Closed by kantord** 2024-04-28 20:38 UTC
