### ISSUE TITLE
Server error when creating account

### ISSUE THREAD

**Issue by RayBB** [LibreLingo/LibreLingo#2820] opened 2023-04-16 02:03 UTC
When creating a new account, that fails an in red text js shown: server error

Re-posting from https://github.com/LibreLingo/LibreLingo-ES-from-EN/issues/14 since this seems like the correct repo and it's still an issue.

Hope this can be fixed soon. I've been enjoying the site just from one computer for now.

Appreciate all the hard work y'all are putting into this. It is so much nicer than duolingo!

**Comment by prasad5141** [comment] 2023-04-16 18:00
Hi @RayBB,

I checked the above issue, this domain is **sync.librelingo.app** unreachable, because of this we are getting server error on registration page.

who will provide details about this URL **sync.librelingo.app** ?

**Comment by kantord** [comment] 2023-04-17 17:14
Hi, this is a duplicate of this issue: https://github.com/LibreLingo/LibreLingo/issues/2299

**Closed by kantord** 2023-04-17 17:14 UTC
