### ISSUE TITLE
Web app sign up doesn't work and return server error

### ISSUE THREAD

**Issue by erikfazio** [LibreLingo/LibreLingo#3092] opened 2023-09-24 11:58 UTC
I wanted to try the web app because I like the project and I'd like to contribute because I'm a frontend web developer.

I tried to sign up but I receive a server error:

<img width="1920" alt="Schermata 2023-09-24 alle 13 56 18" src="https://github.com/LibreLingo/LibreLingo/assets/24392867/c8881939-b035-4bba-ad6d-42715e0dd538">

In the console I receive the following error when making the request to the register endpoint:

<img width="518" alt="Schermata 2023-09-24 alle 13 56 47" src="https://github.com/LibreLingo/LibreLingo/assets/24392867/9799f1fc-ddc8-4dc3-b5e6-0aaeac384177">

**Comment by hobson** [comment] 2023-12-26 19:22
Same here on Firefox Dec 26

**Comment by hobson** [comment] 2023-12-26 19:23
Duplicate of #2299

**Closed** 2024-04-28 20:39 UTC
